In [15]:
# import libraries needed for workouts
import pandas as pd

In [16]:
columnsToDisplay = ['Activity Type', 'Date', 'Distance','Avg Speed', 'Avg HR', 'Max HR', 
                    'Moving Time', 'Min Elevation', 'Max Elevation']

# read csv file, display only desired columns 
df = pd.read_csv('/Users/paulostos/Desktop/Garmin/Activities.csv', usecols=columnsToDisplay)

# display the first few rows of the DataFrame 
print(df.head())

  Activity Type                 Date  Distance  Avg HR  Max HR Avg Speed  \
0       Cycling  2020-11-13 17:41:02      8.45     154     177      17.9
1       Cycling  2020-11-14 12:15:30     20.74     141     173      16.1
2       Cycling  2020-11-15 16:54:43      4.95      89     118       8.5
3       Cycling  2020-11-16 15:15:08     10.92     145     174      17.6
4       Cycling  2020-11-20 17:31:43      9.07     147     177      17.2

  Moving Time Min Elevation Max Elevation
0    00:28:03           666           770
1    01:16:55           666           833
2    00:34:17           409           659
3    00:36:49           423           541
4    00:31:10           344           459

In [17]:
df.loc[:, 'Date'] = pd.to_datetime(df['Date'])
display(df.head(10))

,Activity Type,Date,Distance,Avg HR,Max HR,Avg Speed,Moving Time,Min Elevation,Max Elevation
0,Cycling,2020-11-13 17:41:02,8.45,154,177,17.9,00:28:03,666,770
1,Cycling,2020-11-14 12:15:30,20.74,141,173,16.1,01:16:55,666,833
2,Cycling,2020-11-15 16:54:43,4.95,89,118,8.5,00:34:17,409,659
3,Cycling,2020-11-16 15:15:08,10.92,145,174,17.6,00:36:49,423,541
4,Cycling,2020-11-20 17:31:43,9.07,147,177,17.2,00:31:10,344,459
5,Cycling,2020-11-21 11:25:32,22.01,143,168,17.1,01:16:49,358,501
6,Cycling,2020-11-23 14:48:14,13.77,132,161,14.7,00:51:31,367,560
7,Cycling,2020-11-24 12:59:20,12.30,152,176,17.2,00:42:49,713,822
8,Cycling,2020-11-25 14:53:59,15.05,145,175,18.3,00:49:18,782,"1,006"
9,Cycling,2020-11-26 14:59:38,8.31,133,162,16.9,00:29:11,952,"1,072"

In [18]:
# Convert 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Now extract the year
df['Year'] = df['Date'].dt.year

# Group the activities by 'Year'
groupedByYear = df.groupby('Year')

# Access the data points for each year
data_2021 = groupedByYear.get_group(2021)
data_2022 = groupedByYear.get_group(2022)
data_2023 = groupedByYear.get_group(2023)
data_2024 = groupedByYear.get_group(2024)

In [19]:
# get the distance traveled for each year 
totalDistancePerYear = df.groupby('Year')['Distance'].sum()

# display data per year 
for year, miles in totalDistancePerYear.items(): 
    print(f"Total distance for {year}: {miles} miles.")

Total distance for 2020: 307.72 miles.
Total distance for 2021: 764.4399999999999 miles.
Total distance for 2022: 297.77 miles.
Total distance for 2023: 993.97 miles.
Total distance for 2024: 1250.23 miles.

In [20]:
# calculate the average heart rate for each year
averageHRPerYear = df.groupby('Year')['Avg HR'].mean()

# loop through each year and its corresponding average heart rate
for year, bpm in averageHRPerYear.items(): 
    print(f"Average HR for {year}: {int(bpm)} BPM. ")

print() 

# calculate the maximum heart rate for each year
maxHRPerYear = df.groupby('Year')['Max HR'].mean()

# loop through each year and its corresponding maximum heart rate
for year, bpm in maxHRPerYear.items(): 
    print(f"Max HR for {year}: {int(bpm)} BPM. ")

Average HR for 2020: 138 BPM.
Average HR for 2021: 142 BPM.
Average HR for 2022: 148 BPM.
Average HR for 2023: 139 BPM.
Average HR for 2024: 137 BPM.

Max HR for 2020: 165 BPM.
Max HR for 2021: 170 BPM.
Max HR for 2022: 174 BPM.
Max HR for 2023: 173 BPM.
Max HR for 2024: 171 BPM.

In [21]:
# check for any invalid or NaN values in the 'Moving Time' column
# print(df['Moving Time'].isna().sum())  # check for NaNs
# print(df['Moving Time'].unique())  # view unique entries

# clean the 'Moving Time' column
# replace invalid entries with a default value (e.g., '00:00:00')
df['Moving Time'] = df['Moving Time'].replace(['NaN', '00:NaN:NaN'], '00:00:00')

# convert the 'Moving Time' column to timedelta
df['Moving Time'] = pd.to_timedelta(df['Moving Time'], errors='coerce')

print()

# group by year and sum the moving time
totalMovingTimePerYear = df.groupby('Year')['Moving Time'].sum()

# loop through each year and print total moving time in hours
for year, time_delta in totalMovingTimePerYear.items(): 
    # convert total timedelta to hours
    total_hours = time_delta.total_seconds() / 3600
    print(f"Total moving time for {year}: {total_hours:.2f} hours.")

Total moving time for 2020: 16.75 hours.
Total moving time for 2021: 42.75 hours.
Total moving time for 2022: 17.27 hours.
Total moving time for 2023: 62.11 hours.
Total moving time for 2024: 77.29 hours.

In [22]:
# Clean the 'Avg Speed' column
df['Avg Speed'] = df['Avg Speed'].replace('--', pd.NA)  # Replace '--' with NaN
df['Avg Speed'] = pd.to_numeric(df['Avg Speed'], errors='coerce')  # Convert to numeric

# Check and handle NaN values
df = df.dropna(subset=['Avg Speed'])  # Drop rows with NaN in 'Avg Speed'

# Calculate the average speed for each year
averageSpeedPerYear = df.groupby('Year')['Avg Speed'].mean().reset_index()

# Loop through the results and print average speed per year
for index, row in averageSpeedPerYear.iterrows():
    year = row['Year']
    mph = row['Avg Speed']
    print(f"Average speed for {int(year)}: {mph:.2f} mph.")

Average speed for 2020: 16.30 mph.
Average speed for 2021: 15.79 mph.
Average speed for 2022: 16.16 mph.
Average speed for 2023: 15.97 mph.
Average speed for 2024: 16.32 mph.